version: "3.9"

services:
  frontend:
    build: ./frontend
    image: ramboo2023/fullstack-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: ramboo2023/fullstack-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=mydb
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db-data:

